#!/usr/bin/python
import smtplib
from email.mime.text import MIMEText
import datetime
import os

MESSAGE = \
"""Dear {username}

This is a friendly reminder about your {name} schedule.  It is {date}, which
means that you should be on {progress} by now."""
SUBJECT = "Progress on project {name}"

def send_mail(to, subject, message):
  frm = 'noreply@localhost'

  msg = MIMEText(message)
  msg['Subject'] = subject
  msg['To'] = to
  msg['From'] = frm
  s = smtplib.SMTP('localhost')
  s.sendmail(frm, [to], msg.as_string())
  s.quit()

def send_reminder(config):
  sep = (config['end_date'] - config['start_date']).days / config['num_reminders']
  tod = (datetime.date.today() - config['start_date']).days
  progress = config['get_progress'](tod / sep)
  info = {
      'username' : config['username'],
      'name'     : config['name'],
      'date'     : datetime.date.today().strftime("%d %B"),
      'progress' : progress,
      }
  send_mail(config['email'],
      SUBJECT.format(**info),
      MESSAGE.format(**info))

def should_send_reminder(config):
  if datetime.date.today() > config['end_date']:
    return False
  if datetime.date.today() < config['start_date']:
    return False
  sep = (config['end_date'] - config['start_date']).days / config['num_reminders']
  tod = (datetime.date.today() - config['start_date']).days
  return tod % sep == 0

def get_configuration(path):
  return config.getConfiguration(path)

def get_config_file(filetree_name):
  return os.environ['HOME']+'/.schedule/'+filetree_name+'.cfg'

def get_all_project_filetree_names():
  for i in os.listdir(os.environ['HOME']+'/.schedule'):
    if i[-4:] == '.cfg':
      yield i[:-4]

def get_jsonable_description(filetree_name):
  config = get_configuration(get_config_file(filetree_name))
  ans = {
      'name': config['name'],
      'filetree_name': filetree_name,
      'start_date': config['start_date'].strftime('%Y-%m-%d'),
      'end_date': config['end_date'].strftime('%Y-%m-%d'),
      }
  return ans

def get_all_projects_json():
  ans = []
  for i in get_all_project_filetree_names():
    ans.append(get_jsonable_description(i))
  return json.dumps(ans)

if __name__ == "__main__":
  import argparse
  import config
  parser = argparse.ArgumentParser()
  subparsers = parser.add_subparsers(dest='action')
  subparsers.add_parser('sendmail', help='sendmail')
  query_parser = subparsers.add_parser('query', help='query')
  query_parser.add_argument('entity', choices=['projects'])
  args = parser.parse_args()

  if args.action == 'sendmail':
    for i in get_all_project_filetree_names():
      configuration = get_configuration(get_config_file(i))
      if should_send_reminder(configuration):
        send_reminder(configuration)
  elif args.action == 'query':
    import json
    if args.entity == 'projects':
      print get_all_projects_json()
